db.users.insert({
  _id: ObjectId("5c962bccf0b0d14286e99b68"),
  joined: Date.now(),
  lastOnline: Date.now(),
  lastUpdated: Date.now(),
  isVerified: false,
  verificationToken: '',
  verificationTokenExpiry: Date.now(),
  email: 'sweetbot@example.com',
  username: 'sweetbot',
  password: 'invalid password hash',
  passwordResetToken: '',
  passwordResetTokenExpiry: Date.now(),
  image: '',
  imageEnabled: false,
  displayName: 'SweetBot',
  pronouns: 'bot/bot',
  aboutRaw: '',
  aboutParsed: '',
  websiteRaw: '',
  websiteParsed: '',
  location: '',
  notifications: [],
  pushNotifSubscriptions: [],
  communities: [],
  bannedCommunities: [],
  mutedCommunities: [],
  hiddenRecommendedUsers: [],
  hiddenRecommendedCommunities: [],
  settings: {
    timezone: 'auto',
    autoDetectedTimeZone: '',
    profileVisibility: 'invisible',
    newPostPrivacy: 'public',
    imageQuality: 'standard',
    homeTagTimelineSorting: 'fluid',
    userTimelineSorting: 'chronological',
    communityTimelineSorting: 'fluid',
    flashRecentComments: true,
    digestEmailFrequency: 'off',
    emailTime: '17:00',
    emailDay: 'Sunday',
    showRecommendations: true,
    showHashtags: true,
    sendMentionEmails: true
  }
})
