FROM node:14

ENV NODE_ENV development
ENV TINI_VERSION v0.19.0

# use tini as init
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /sbin/tini
RUN chmod +x /sbin/tini

EXPOSE 8686

WORKDIR /usr/src/app

COPY package*.json yarn.lock ./

RUN yarn install \
      --frozen-lockfile

COPY . .

USER node

ENTRYPOINT ["/sbin/tini", "--", "docker-entrypoint.sh"]
CMD ["yarn", "start"]
